function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('overflow',!0,!0);noOverflowEvent.initEvent('nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('overflow',function(){t228_checkOverflow(recid)});$(menuBlock).on('overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('nooverflow',function(){t228_checkNoOverflow(recid)});$(menuBlock).on('nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t228__list_item a[href=\''+url+'\'], '+'.t228__list_item a[href=\''+url+'/\'], '+'.t228__list_item a[href=\''+pathname+'\'], '+'.t228__list_item a[href=\'/'+pathname+'\'], '+'.t228__list_item a[href=\''+pathname+'/\'], '+'.t228__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t228_checkAnchorLinks(recid){if(window.innerWidth>=980){var rec=document.getElementById('rec'+recid);var navLinks=rec?rec.querySelectorAll('.t228__list_item a[href*=\'#\']'):[];navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){setTimeout(function(){t228_catchScroll(navLinks)},500)}}}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',(windowHeight-mobileContainerHeight)+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t228_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});sections.sort(function(a,b){return b.getBoundingClientRect().top-a.getBoundingClientRect().top});t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t228_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t228_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getBoundingClientRect().top+window.pageYOffset;var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px';if(menuList)menuList.classList.remove('t228__list_hidden')}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t228_setBg(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t228_appearMenu(recid){if(window.innerWidth<=980)return;var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t228_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t228_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t228_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t228_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t228');var burger=rec.querySelector('.t228__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t228_opened')){t228_fadeOut(menu,300);burger.classList.remove('t228_opened')}else{t228_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t228_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu.style.opacity)menu.style.opacity='';if(menu.style.display==='none')menu.style.display=''}else if(menu.style.transform)menu.style.transform=''}))}
function t228_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t228_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t228_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t270_scroll(hash,offset,speed){if(!speed)speed=400;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;if(!hash)return;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);t270_scrollToEl(target);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_scrollToEl(target,duration){if(!duration){duration=400}
if(target===window.pageYOffset){return!1}
var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(Math.abs(window.pageYOffset-target)*10)/duration;var scrollInterval=setInterval(function(){if(cashedDiff>target){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>target&&window.pageYOffset<=target){document.body.removeAttribute('data-scrollable');clearInterval(scrollInterval)}else if(cashedDiff<=target&&window.pageYOffset>=target){document.body.removeAttribute('data-scrollable');window.scrollTo(0,target);clearInterval(scrollInterval)}},10);var scrollTimeout=setTimeout(function(){clearInterval(scrollInterval);document.body.removeAttribute('data-scrollable');clearTimeout(scrollTimeout)},duration*2)}
function t280_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);var isAndroid=/(android)/i.test(navigator.userAgent);var menu=rec.querySelector('.t280');var menuItems=rec.querySelectorAll('.t280__menu__item');var menuLinks=rec.querySelectorAll('.t978__menu-link');var menuContainer=rec.querySelector('.t280__menu');var clickElementsList=rec.querySelectorAll('.t280__burger, .t280__menu__bg, .t280__menu__item:not(.tooltipstered):not(.t280__menu__item_submenu), .t978__tooltip-menu_mobile');Array.prototype.forEach.call(clickElementsList,function(clickElement){clickElement.addEventListener('click',function(){if(clickElement.closest('.t280__menu__item.tooltipstered')||clickElement.closest('.t794__tm-link'))return;if(isChrome&&isAndroid&&menuItems.length>10&&window.location.hash){setTimeout(function(){var hash=window.location.hash;window.location.hash='';window.location.hash=hash},50)}
if(!clickElement.closest('.t978__tm-link, .t966__tm-link')){document.body.classList.toggle('t280_opened');if(menu)menu.classList.toggle('t280__main_opened');var menuHead=rec.querySelector('.t280__container');if(menuContainer)menuContainer.style.paddingTop=(menuHead?menuHead.offsetHeight:0)+'px'}
t280_changeSize(recid);t280_highlight(recid)})});document.addEventListener('click',function(e){if(e.target.closest('.t978__tm-link, .t966__tm-link, .t-menusub__target-link')){t280_changeSize(recid);if(menuContainer)menuContainer.style.transition='none'}});Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t280_changeSize(recid)})});if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){document.body.classList.remove('t280_opened');menu.classList.remove('t280__main_opened')})}
var submenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){document.body.classList.remove('t280_opened');if(menu)menu.classList.remove('t280__main_opened')})})}
function t280_changeSize(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t280__menu');var menuBottom=rec.querySelector('.t280__bottom');var menuContainer=rec.querySelector('.t280__container');var menuWrapper=rec.querySelector('.t280__menu__wrapper');setTimeout(function(){var menuHeight=menu?menu.offsetHeight:0;var menuBottomHeight=menuBottom?menuBottom.offsetHeight:0;var menuContainerHeight=menuContainer?menuContainer.offsetHeight:0;var padding=140;if(menuHeight>document.documentElement.clientHeight-(menuBottomHeight+menuContainerHeight+padding)){if(menuWrapper)menuWrapper.classList.add('t280__menu_static')}else{if(menuWrapper)menuWrapper.classList.remove('t280__menu_static')}})}
function t280_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t280__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadow=menu.getAttribute('data-menu-shadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t280_appearMenu(){var menuBlocks=document.querySelectorAll('.t280');Array.prototype.forEach.call(menuBlocks,function(menuBlock){var menu=menuBlock.querySelector('.t280__positionfixed');if(menu){var appearOffset=menuBlock.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t280_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t280_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t280_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t280__menu a[href=\''+url+'\'], '+'.t280__menu a[href=\''+url+'/\'], '+'.t280__menu a[href=\''+pathname+'\'], '+'.t280__menu a[href=\'/'+pathname+'\'], '+'.t280__menu a[href=\''+pathname+'/\'], '+'.t280__menu a[href=\'/'+pathname+'/\']'+(hash?', .t280__menu a[href=\''+hash+'\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'\']':'')+(hash?', .t280__menu a[href=\''+hash+'/\']':'')+(hash?', .t280__menu a[href=\'/'+hash+'/\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t280__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t331_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;rec.setAttribute('data-animationappear','off');rec.style.opacity='1';var currentBlock=rec.querySelector('.t-popup');var currentHook=currentBlock?currentBlock.getAttribute('data-tooltip-hook'):'';var currentAnalitics=currentBlock?currentBlock.getAttribute('data-track-popup'):'';if(!currentHook)return!1;document.addEventListener('click',function(e){if(e.target.closest('a[href="'+currentHook+'"]')){e.preventDefault();t331_showPopup(recid);t331_resizePopup(recid);if(currentAnalitics){var virtTitle=currentHook;if(virtTitle.substring(0,7)==='#popup:')virtTitle=virtTitle.substring(7);Tilda.sendEventToStatistics(currentAnalitics,virtTitle)}}})}
function t331_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var videoCarrier=rec.querySelector('.t331__video-carier');var carrierParent=videoCarrier?videoCarrier.parentNode:null;var videoWidth=videoCarrier?videoCarrier.getAttribute('data-video-width'):'0';var videoHeight=videoCarrier?videoCarrier.getAttribute('data-video-height'):'0';if(videoHeight.indexOf('vh')!==-1){videoHeight=parseInt(videoHeight,10)*window.innerHeight/100}else{videoHeight=parseInt(videoHeight,10)}
var ratio=videoHeight/(parseInt(videoWidth,10)||1);var videoCurrentWidth=videoCarrier?videoCarrier.offsetWidth:0;var calculatedHeight=videoCurrentWidth*ratio;if(videoCarrier)videoCarrier.style.height=calculatedHeight+'px';if(carrierParent)carrierParent.style.height=calculatedHeight+'px'}
function t331_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var popup=rec.querySelector('.t-popup');var videoContainer=rec.querySelector('.t331__youtube');var videoCarrier=rec.querySelector('.t331__video-carier');var isVideoCarrierExist=!!videoCarrier.querySelector('iframe');if(isVideoCarrierExist)return;var videoID=videoContainer?videoContainer.getAttribute('data-content-popup-video-url-youtube'):'';var videoURL=videoID?'https://www.youtube.com/embed/'+videoID:'';if(videoCarrier){var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+recid;iframe.classList.add('t331__iframe');iframe.width='100%';iframe.height='100%';iframe.src=videoURL+(videoURL.indexOf('?')!==-1?'&':'?')+'autoplay=1&rel=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');videoCarrier.insertAdjacentElement('beforeend',iframe)}
if(popup)popup.style.display='block';t331_setHeight(recid);setTimeout(function(){var popupContainer=popup?popup.querySelector('.t-popup__container'):null;if(popupContainer)popupContainer.classList.add('t-popup__container-animated');if(popup)popup.classList.add('t-popup_show')},50);document.body.classList.add('t-body_popupshowed');document.body.classList.add('t331__body_popupshowed');if(popup){popup.addEventListener('click',function(e){if(e.target===popup)t331_popup_close(recid)})}
var popupClose=popup?popup.querySelector('.t-popup__close'):null;if(popupClose){popupClose.addEventListener('click',function(){t331_popup_close(recid)})}
document.addEventListener('keydown',function(e){if(e.keyCode===27)t331_popup_close(recid)})}
function t331_popup_close(recid){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t331__body_popupshowed');var rec=document.getElementById('rec'+recid);if(!rec)return!1;var popup=rec.querySelector('.t-popup');var videoCarrier=rec.querySelector('.t331__video-carier');if(popup)popup.classList.remove('t-popup_show');setTimeout(function(){if(videoCarrier)videoCarrier.innerHTML='';if(popup&&!popup.classList.contains('t-popup_show')){popup.style.display='none'}},300)}
function t331_resizePopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var popupContainer=rec.querySelector('.t-popup__container');var popupContainerHeight=popupContainer?popupContainer.offsetHeight:0;if(popupContainerHeight>window.innerHeight){if(popupContainer){popupContainer.classList.add('t-popup__container-static')}}else if(popupContainer){popupContainer.classList.remove('t-popup__container-static')}}
function t331_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)==='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!=='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t404_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var mainContainer=rec.querySelector('.t404');if(!mainContainer)return;var containers=rec.querySelectorAll('.t-container');for(var i=0;i<containers.length;i++){var container=containers[i];var titles=container.querySelectorAll('.t404__title');var descrs=container.querySelectorAll('.t404__descr');var maxHeight=0;for(var j=0;j<titles.length;j++){var title=titles[j];title.style.height='';var titleStyle=getComputedStyle(title,null);var titlePaddingTop=parseInt(titleStyle.paddingTop)||0;var titlePaddingBottom=parseInt(titleStyle.paddingBottom)||0;var titleHeight=title.clientHeight-(titlePaddingTop+titlePaddingBottom);if(titleHeight>maxHeight)maxHeight=titleHeight}
if(window.innerWidth>=960){for(var j=0;j<titles.length;j++){titles[j].style.height=maxHeight+'px'}}else{for(var j=0;j<titles.length;j++){titles[j].style.height='auto'}}
maxHeight=0;for(var j=0;j<descrs.length;j++){var descr=descrs[j];descr.style.height='';var descrStyle=getComputedStyle(descr,null);var descrPaddingTop=parseInt(descrStyle.paddingTop)||0;var descrPaddingBottom=parseInt(descrStyle.paddingBottom)||0;var descrHeight=descr.clientHeight-(descrPaddingTop+descrPaddingBottom);if(descrHeight>maxHeight)maxHeight=descrHeight}
if(window.innerWidth>=960){for(var j=0;j<descrs.length;j++){descrs[j].style.height=maxHeight+'px'}}else{for(var j=0;j<descrs.length;j++){descrs[j].style.height='auto'}}}}
function t404_unifyHeightsTextwrapper(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var mainContainer=rec.querySelector('.t404');if(!mainContainer)return;var containers=rec.querySelectorAll('.t-container');for(var i=0;i<containers.length;i++){var container=containers[i];var textWrappers=container.querySelectorAll('.t404__textwrapper');var maxHeight=0;for(var j=0;j<textWrappers.length;j++){var textWrapper=textWrappers[j];textWrapper.style.height='auto';var textWrapperStyle=getComputedStyle(textWrapper,null);var textWrapperPaddingTop=parseInt(textWrapperStyle.paddingTop)||0;var textWrapperPaddingBottom=parseInt(textWrapperStyle.paddingBottom)||0;var textWrapperHeight=textWrapper.clientHeight-(textWrapperPaddingTop+textWrapperPaddingBottom);if(textWrapperHeight>maxHeight)maxHeight=textWrapperHeight}
if(window.innerWidth>=960){for(var j=0;j<textWrappers.length;j++){textWrappers[j].style.height=maxHeight+'px'}}else{for(var j=0;j<textWrappers.length;j++){textWrappers[j].style.height='auto'}}}}
function t404_showMore(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t404');if(!container)return;var cols=container.querySelectorAll('.t-col');var allRecords=document.getElementById('allrecords');for(var i=0;i<cols.length;i++){cols[i].style.display='none'}
var cardsLength=cols.length;var cardsCount=parseInt(container.getAttribute('data-show-count'),10);if(cardsCount>500)cardsCount=500;var startIndexShowBlock=cardsCount;var countShowBlock=cardsCount;var colsShow=t404__getShowBlocks(cols,startIndexShowBlock);for(var i=0;i<colsShow.length;i++){colsShow[i].style.display='block'}
var showMoreBtn=rec.querySelector('.t404__showmore');if(showMoreBtn){showMoreBtn.addEventListener('click',function(){startIndexShowBlock=(startIndexShowBlock+countShowBlock<=cardsLength)?startIndexShowBlock+countShowBlock:cardsLength;var newColsShow=t404__getShowBlocks(cols,startIndexShowBlock);for(var i=0;i<newColsShow.length;i++){newColsShow[i].style.display='block'}
if(startIndexShowBlock===cardsLength){showMoreBtn.style.display='none'}
t404__triggerEvent(container,'displayChanged');if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t404__getShowBlocks(elements,index){var newElements=[];for(var i=0;i<elements.length;i++){if(i<=index-1)newElements.push(elements[i])}
return newElements}
function t404__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}
if(t404__checkJqueryEvent(el,eventName)){$(el).trigger(eventName)}}
function t404__checkJqueryEvent(element,eventName){var events=$._data(element,'events')||!1;var isEvent=!1;if(events){for(var key in events){if(key===eventName){isEvent=!0;break}}}
return isEvent}
function t480_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var isJquery=typeof jQuery!=='undefined';t480_setHeight(recId);if(window.isMobile){if(isJquery){$(window).on('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}else{window.addEventListener('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}}else{window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t480_setHeight(recId)}))}
if(isJquery){$(container).on('displayChanged',function(){t480_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t480_setHeight(recId)})}}
function t480_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var sizer=rec.querySelector('.t480__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var imgWrapper=rec.querySelector('.t480__blockimg');var imgWidth=imgWrapper.clientWidth;var sizerAttrStyle=sizer.getAttribute('style');var windowHeight=window.innerHeight;if(window.isMobile&&sizerAttrStyle&&sizerAttrStyle.indexOf('vh')!==-1){sizerHeight=document.documentElement.clientHeight*parseFloat(windowHeight/sizerHeight);imgWrapper.style.height=(imgWidth/ratio)+'px'}else if(sizerHeight!=windowHeight){imgWrapper.style.height=(imgWidth/ratio)+'px'}}
function t650_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t650');if(!container)return;var rows=rec.querySelectorAll('.t650__row');if(window.innerWidth>=960){for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t650__inner-col');for(var j=0;j<cols.length;j++){var col=cols[j];var colText=col.querySelector('.t650__text');var colBtn=col.querySelector('.t650__btn-container');var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<cols.length;j++){cols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t650__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var videoType=play.getAttribute('data-slider-video-type');var url;var nextEl;var prevEl;var iframe;var video;var source;switch(videoType){case 'youtube':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'vimeo':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay; fullscreen');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'mp4':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){video=document.createElement('video');source=document.createElement('source');video.insertAdjacentElement('beforeend',source);video.classList.add('t670__video');video.controls=!0;source.src=url;nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',video)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break}
if(nextEl)nextEl.style.zIndex='3'})})}
function t670_hide(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var elBody=rec.querySelector('.t670__frame');rec.addEventListener('updateSlider',function(){if(elBody)elBody.innerHTML='';if(elBody)elBody.style.zIndex=''})}
function t670_imageHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=img.getAttribute('data-slider-image-width')||0;var height=img.getAttribute('data-slider-image-height')||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t694_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t694');if(!container)return;t694_setHeight(recId);setTimeout(function(){t694_setHeight(recId)},500);window.addEventListener('resize',t_throttle(function(){t694_setHeight(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t694_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t694_setHeight(recId)})}}
function t694_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t694');if(!container)return;var rows=rec.querySelectorAll('.t694__row');var col=rec.querySelector('.t694__col');var ratio=container.getAttribute('data-tile-ratio');if(!col)return;var colStyle=getComputedStyle(col,null);var colPaddingLeft=parseInt(colStyle.paddingLeft)||0;var colPaddingRight=parseInt(colStyle.paddingRight)||0;var colHeight=(col.clientWidth-(colPaddingLeft+colPaddingRight))*+ratio;var maxHeight=0;if(window.innerWidth>=768){for(var i=0;i<rows.length;i++){var row=rows[i];var tables=row.querySelectorAll('.t694__table');for(var j=0;j<tables.length;j++){var table=tables[j];var textWrapHeight=table.querySelector('.t694__textwrapper').offsetHeight;var cell=table.querySelector('.t694__cell');if(cell.classList.contains('t694__button-bottom')){textWrapHeight+=table.querySelector('.t694__button-container').offsetHeight}
if(textWrapHeight>maxHeight)maxHeight=textWrapHeight}
if(maxHeight>colHeight){for(var j=0;j<tables.length;j++){tables[j].style.height=maxHeight+'px'}}else{for(var j=0;j<tables.length;j++){tables[j].style.height=''}}}}else{var tables=rec.querySelectorAll('.t694__table');for(var i=0;i<tables.length;i++){tables[i].style.height=''}}}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t823_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t823__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t823__fadeOut(tildaLabel)}},300)}else{t823__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t823__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t823__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t823__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t823__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t823__animateScroll(){currentTime+=increment;window.scrollTo(0,t823__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t823__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t823__animateScroll()}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var button=rec.querySelector('.t890__arrow');var windowOffset='';if(offset){windowOffset=offset}else{windowOffset=window.innerHeight}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));button.addEventListener('click',t890__scrollToTop)}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t983_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t983');if(!container)return;window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t983_unifyHeights(recId);t983_translateBlock(recId)}));window.addEventListener('load',function(){t983_unifyHeights(recId);t983_translateBlock(recId)});if(typeof jQuery!=='undefined'){$(container).on('displayChanged',t_throttle(function(){t983_unifyHeights(recId);t983_translateBlock(recId)}))}else{container.addEventListener('displayChanged',t_throttle(function(){t983_unifyHeights(recId);t983_translateBlock(recId)}))}
t983_unifyHeights(recId);t983_translateBlock(recId);t983__updateLazyLoad(recId)}
function t983_translateBlock(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t983');if(!container)return;var hoverBlocks=rec.querySelectorAll('.t983__card-block_hover');var wrapMarginBottom=35;var isMobile=window.isMobile||window.innerWidth<960;for(var i=0;i<hoverBlocks.length;i++){var hoverBlock=hoverBlocks[i];var blockWrapper=t983_getParent(hoverBlock,'t983__card-block-wrapper');var card=t983_getParent(hoverBlock,'t983__card');var cardHeight=card.clientHeight;var diff=cardHeight-hoverBlock.offsetHeight-wrapMarginBottom*2;var cardHideDiff=hoverBlock.querySelector('.t983__card-hide').offsetHeight;blockWrapper.style.transform='translateY('+diff+'px)';if(!isMobile){hoverBlock.style.transform='translateY('+cardHideDiff+'px)'}else{hoverBlock.style.transform=null}}
if(hoverBlocks.length===0){var rows=(isMobile?rec.querySelectorAll('.t983__container'):rec.querySelectorAll('.t983__row'));for(var i=0;i<rows.length;i++){var row=rows[i];var cardBlocks=row.querySelectorAll('.t983__card-block');var maxHeightRow=0;var card=t983_getParent(cardBlocks[0],'t983__card');var cardStyle=getComputedStyle(card,null);var cardPaddingTop=parseInt(cardStyle.paddingTop)||0;var cardPaddingBottom=parseInt(cardStyle.paddingBottom)||0;var cardHeight=card.clientHeight-(cardPaddingTop+cardPaddingBottom);for(var j=0;j<cardBlocks.length;j++){var cardHide=cardBlocks[j].querySelector('.t983__card-hide');var cardHideHeight=cardHide?cardHide.offsetHeight:0;if(cardHideHeight>maxHeightRow)maxHeightRow=cardHideHeight}
for(var j=0;j<cardBlocks.length;j++){var cardBlock=cardBlocks[j];var cardShow=cardBlock.querySelector('.t983__card-show');var cardShowHeight=cardShow?cardShow.offsetHeight:0;var diff=cardHeight-cardShowHeight-maxHeightRow-wrapMarginBottom*2;cardBlock.style.transform='translateY('+diff+'px)'}}}}
function t983_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var main=rec.querySelector('.t983');if(!main)return;var container=rec.querySelector('.t983__container');var rows=main.querySelectorAll('.t983__row');for(var i=0;i<rows.length;i++){var row=rows[i];var cardsContent=row.querySelectorAll('.t983__card-content');var cardsWrapper=row.querySelectorAll('.t983__card-wrapper');var card=row.querySelector('.t983__card');var cardStyle=getComputedStyle(card,null);var cardPaddingLeft=parseInt(cardStyle.paddingLeft)||0;var cardPaddingRight=parseInt(cardStyle.paddingRight)||0;var cardWidth=card.clientWidth-(cardPaddingLeft+cardPaddingRight);var maxHeight=0;var ratio=container.getAttribute('data-ratio');var minHeightFromRatio=0;switch(ratio){case '16_9':minHeightFromRatio=cardWidth*0.5625;break;case '4_3':minHeightFromRatio=cardWidth*0.75;break;case '3_2':minHeightFromRatio=cardWidth*0.6666;break;case '1_1':minHeightFromRatio=cardWidth;break;case '2_3':minHeightFromRatio=cardWidth*1.5;break;case '3_4':minHeightFromRatio=cardWidth*1.3333;break;case '9_16':minHeightFromRatio=cardWidth*1.7777;break}
for(var j=0;j<cardsContent.length;j++){var cardContentHeight=cardsContent[j].offsetHeight;if(cardContentHeight>maxHeight)maxHeight=cardContentHeight}
if(maxHeight>minHeightFromRatio){for(var j=0;j<cardsWrapper.length;j++){cardsWrapper[j].style.paddingBottom=maxHeight+'px'}}else{for(var j=0;j<cardsWrapper.length;j++){cardsWrapper[j].style.paddingBottom=null}}}}
function t983__updateLazyLoad(recId){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){var scrollContainer=document.querySelector('#rec'+recId+' .t983__container_mobile-flex');var curMode=allRecords.getAttribute('data-tilda-mode');if(scrollContainer&&curMode!='edit'&&curMode!='preview'&&window.isMobile){scrollContainer.addEventListener('touchmove',t_throttle(function(){t_lazyload_update()}))}})}}
function t983_getParent(element,className){for(var p=element&&element.parentElement;p;p=p.parentElement){if(p.classList.contains(className)){return p}}}